"""Widget collection and screen/build_xml methods for _TriplexExportBuilder."""
from __future__ import annotations

from .triplex_xml_screen_collect import _XmlScreenCollectMixin

import hashlib
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple
import xml.etree.ElementTree as ET



class _XmlScreenMixin(_XmlScreenCollectMixin):
    """Widget collection, screen layout, and the public build_xml() entry point."""

    def _build_screen_elements(
            self,
            data: Any,
            widgets: List[Dict[str, Any]],
            screen_width: int,
            screen_height: int,
            palette_final: str,
            palette_name: str,
        ) -> None:
            """Append palette (t63), screen (t17–t19), and empty UI stubs (t20–t46) to *data*."""
            if self._palette_colors:
                palette_value = ",".join(hex_color for _, hex_color in self._palette_colors)
                t63 = ET.SubElement(data, "t63", attrib={"sCheck": "54"})
                ET.SubElement(t63, "r", attrib={
                    "nid": str(self.palette_id),
                    "sname": palette_name,
                    "svalue": palette_value,
                })

            # t17 - ui.tscreen_v30
            screen_title = f"{self.dashboard_title} - Main"
            t17 = ET.SubElement(data, "t17", attrib={"sCheck": "672"})
            ET.SubElement(t17, "r", attrib={
                "nid": str(self.screen_id),
                "ndashboardid": str(self.dashboard_id),
                "sname_ru": screen_title,
                "sname_en": screen_title,
                "ntype": "1",
                "nshrinktype": "1",
                "nwidth": str(screen_width),
                "nheight": str(screen_height),
                "norder": "1",
                "stitle_ru": self.dashboard_title,
                "stitle_en": self.dashboard_title,
                "ishidebreadcrumbs": "false",
                "isdisablepadding": "false",
                "nlayouttype": "1",
                "isstretchlastwidgettotheendofscreen": "false",
                "isstretchallwidgetstothesidesofscreen": "false",
                "isexportpdf": "false",
            })

            # t18 - ui.tscreensection_v30 (screen sections)
            section_id = self._next_id()
            t18 = ET.SubElement(data, "t18", attrib={"sCheck": "145"})
            ET.SubElement(t18, "r", attrib={
                "nid": str(section_id),
                "nscreenid": str(self.screen_id),
                "sname_ru": "Основная",
                "nord": "1",
                "ishidetitle": "false",
                "spropertiessql": "",
            })

            # t19 - ui.tscreenwidget_v30
            t19 = ET.SubElement(data, "t19", attrib={"sCheck": "750"})
            for widget in widgets:
                ET.SubElement(t19, "r", attrib=widget)

            # t20 - ui.tcontrolobject_v30 (empty - no controls by default)
            ET.SubElement(data, "t20", attrib={"sCheck": "924"})
            # t21 - ui.tscreenwidgetparameters_v30 (empty)
            ET.SubElement(data, "t21", attrib={"sCheck": "91"})
            # t22 - ui.tcombinewidget_v30 (empty)
            ET.SubElement(data, "t22", attrib={"sCheck": "0"})
            # t23 - ui.tcontrolobjectlink_v30 (empty)
            ET.SubElement(data, "t23", attrib={"sCheck": "0"})
            # t24 - ui.tscreenwidgetdisabled_v30 (empty)
            ET.SubElement(data, "t24", attrib={"sCheck": "102"})
            # t25 - ui.tcontrolobjecthiddenscreenwidget_v30 (empty)
            ET.SubElement(data, "t25", attrib={"sCheck": "52"})
            # t33 - ui.tcontrolobjectlinkautogenerated_v30 (empty)
            ET.SubElement(data, "t33", attrib={"sCheck": "59"})
            # t37 - ui.tscreendataset_v30 (empty – not present in Navigator demo exports)
            ET.SubElement(data, "t37", attrib={"sCheck": "0"})
            # t38 - ui.tcontrolobjectdisabled_v30 (empty)
            ET.SubElement(data, "t38", attrib={"sCheck": "0"})

            # Analytical report tables (Navigator "Таблицы") are intentionally
            # omitted. Keep empty containers so import structure remains stable.
            for tag, check in [("t39", "67"), ("t41", "64"), ("t42", "72"), ("t43", "118"),
                               ("t44", "79"), ("t40", "77"), ("t45", "100"), ("t46", "72")]:
                if data.find(tag) is None:
                    ET.SubElement(data, tag, attrib={"sCheck": check})

    def build_xml(self) -> bytes:
        exported_at = datetime.now()
        timestamp = exported_at.strftime("%H:%M %d.%m.%Y")
        dt_last_load = exported_at.strftime("%Y-%m-%d %H:%M:%S.%f")
        check = hashlib.md5(timestamp.encode("utf-8")).hexdigest()
        structure_updates = self._embedded_structure_updates()
        if structure_updates:
            check_d_source = "".join(sql for _, sql in sorted(structure_updates, key=lambda item: item[0]))
        else:
            check_d_source = check
        check_d = hashlib.md5((check_d_source + timestamp).encode("utf-8")).hexdigest()
        self.palette_id = self._palette_id_for_export(exported_at)
        palette_name = self._palette_name_for_export(exported_at)

        root = ET.Element("root", attrib={
            "dtCreateTime": timestamp,
            "Check": check,
            "CheckD": check_d,
        })

        # --- info section ---
        info = ET.SubElement(root, "info", attrib={
            "sComment": "",
            "DBVersion": self.DEFAULT_DB_VERSION,
        })
        subjectarea = ET.SubElement(info, "subjectarea")
        ET.SubElement(subjectarea, "r", attrib={
            "nID": str(self.subject_area_id),
            "sName": self.subject_area_name,
        })

        ET.SubElement(info, "positions")

        dashboards_info = ET.SubElement(info, "dashboards")
        ET.SubElement(dashboards_info, "r", attrib={
            "nID": str(self.dashboard_id),
            "sName": self.dashboard_title,
        })

        ET.SubElement(info, "screens")

        # tables info - will be populated with report names below
        ET.SubElement(info, "tables")

        # sources info - will be populated with user sources below
        sources_info = ET.SubElement(info, "sources")

        ET.SubElement(info, "dictionaries")

        # indicators info - will be populated below
        ET.SubElement(info, "indicators")

        # datamodel info - will be populated with data model below
        datamodel_info = ET.SubElement(info, "datamodel", attrib={"isSaveVersion": "false"})
        ET.SubElement(info, "queuejobs")

        # --- data section ---
        data = ET.SubElement(root, "data")

        # t201 - rm.tsubjectarea
        t201 = ET.SubElement(data, "t201", attrib={"sCheck": "183"})
        ET.SubElement(t201, "r", attrib={
            "nid": str(self.subject_area_id),
            "sname_ru": self.subject_area_name,
            "sname_en": self.subject_area_name,
            "sshortname_ru": self._name_suffix[-10:],
            "sshortname_en": self._name_suffix[-10:],
            "norder": "-1",
            "ndisplaystateid": "7",
            "nshardid": "3",
        })

        # t202 - rme.tsubjectareadashboard
        t202 = ET.SubElement(data, "t202", attrib={"sCheck": "161"})
        ET.SubElement(t202, "r", attrib={
            "nid": str(self.dashboard_id),
            "nsubjectareaid": str(self.subject_area_id),
            "ndashboardid": str(self.dashboard_id),
            "ndashboardord": str(self.dashboard_ord),
            "ndashboardgroupid": "0",
            "isenabledqc": "false",
            "ismainsa": "true",
        })

        # Keep subject-area permission tables present so manual XML imports give
        # the local admin user immediate access. The backend still upserts the
        # same access after API imports.
        admin_user_id = self._coerce_int(self.payload.get("navigator_access_user_id")) or 2
        user_sa_id = self._next_id()
        t203 = ET.SubElement(data, "t203", attrib={"sCheck": "0"})
        ET.SubElement(t203, "r", attrib={
            "nid": str(user_sa_id),
            "nuserid": str(admin_user_id),
            "nsubjectareaid": str(self.subject_area_id),
            "isowner": "true",
            "ismanual": "true",
            "isauto": "false",
            "ismanualglobalroleaccess": "true",
            "isautoglobalroleaccess": "false",
        })
        t204 = ET.SubElement(data, "t204", attrib={"sCheck": "0"})
        ET.SubElement(t204, "r", attrib={
            "nusersubjectareaid": str(user_sa_id),
            "nenvironmentid": "1",
            "ismanual": "true",
            "isauto": "false",
        })
        ET.SubElement(data, "t205", attrib={"sCheck": "0"})

        # t3 - rme.tsubjectareaindicator (link subject area to indicators)
        ET.SubElement(data, "t3", attrib={"sCheck": "82"})

        # t4 - data.kpi_ (indicator/KPI definitions)
        ET.SubElement(data, "t4", attrib={"sCheck": "693"})

        # Do not import Navigator subject-area indicators. Dashboard KPI cards
        # are screen widgets backed by user sources, so t3/t4 can stay empty.

        # t262 - rme.tsubjectareaao (link subject area to reports)
        ET.SubElement(data, "t262", attrib={"sCheck": "115"})

        # t11 - rme.tsubjectareausersource (link subject area to user sources)
        t11 = ET.SubElement(data, "t11", attrib={"sCheck": "52"})

        # t12 - data.tusersource (user source definitions)
        t12 = ET.SubElement(data, "t12", attrib={"sCheck": "270"})

        dv = ET.SubElement(data, "dv")

        # t15 - ui.tdashboard
        t15 = ET.SubElement(data, "t15", attrib={"sCheck": "573"})
        ET.SubElement(t15, "r", attrib={
            "nid": str(self.dashboard_id),
            "ndashboardid": str(self.dashboard_id),
            "nparentdashboardid": "5",
            "ndashboardtypeid": "15",
            "ndashboardposition": "1",
            "ndynamictypeid": "3",
            "nobjecttypeid": "2",
            "ninsidermask": "0",
            "ndisplaystateid": "7",
            "sdashboardtitle_ru": self.dashboard_title,
            "sdashboardtitle_en": self.dashboard_title,
            "ntargetdbplatformtype": "1",
        })

        # t16 - ui.tdicmenuitem
        menu_position = str(self.dashboard_id) if self.dashboard_id > 0 else "1000"
        t16 = ET.SubElement(data, "t16", attrib={"sCheck": "357"})
        ET.SubElement(t16, "r", attrib={
            "nid": str(self.dashboard_id),
            "sname_ru": self.dashboard_title,
            "sname_en": self.dashboard_title,
            "isdefault": "0",
            "nobjectid": str(self.dashboard_id),
            "nmenuitemposition": menu_position,
            "ndisplaystateid": "7",
            "isservice": "false",
            "ndisplayenvironmentid": "1",
            "ndisplayplatformid": "7",
            "ndisplaydbplatformid": "3",
        })

        widgets, widget_datasets, dataset_stable_map = self._collect_widgets()

        # --- Row-preserving layout reflow ---
        # Keep widgets that started on the same source row together, then pack
        # rows from y=0 by the tallest widget in each row. This normalizes
        # Vision/manual layouts that contain suspicious top gaps or row/height
        # mismatches while preserving the horizontal composition.
        if widgets:
            def _widget_layout_key(widget: Dict[str, str]) -> Tuple[int, int, int]:
                return (
                    int(widget.get("_layout_y") or widget["nycoord"]),
                    int(widget.get("_layout_x") or widget["nxcoord"]),
                    int(widget["norder"]),
                )

            current_y = 0
            current_source_y: Optional[int] = None
            current_row_widgets: List[Dict[str, str]] = []

            def flush_row() -> None:
                nonlocal current_y, current_row_widgets
                if not current_row_widgets:
                    return
                column_heights: List[int] = [0] * self.DEFAULT_SCREEN_WIDTH
                for widget in sorted(current_row_widgets, key=lambda item: (int(item["nxcoord"]), int(item["norder"]))):
                    x = max(0, int(widget["nxcoord"]))
                    width = max(1, int(widget["nwidth"]))
                    height = max(1, int(widget["nheight"]))
                    end_x = min(len(column_heights), x + width)
                    packed_offset = max(column_heights[x:end_x], default=0)
                    widget["nycoord"] = str(current_y + packed_offset)
                    next_height = packed_offset + height
                    for column_idx in range(x, end_x):
                        column_heights[column_idx] = next_height
                row_height = max(column_heights) if column_heights else 0
                current_y += row_height
                current_row_widgets = []

            for widget in sorted(widgets, key=_widget_layout_key):
                source_y = int(widget.get("_layout_y") or widget["nycoord"])
                if current_source_y is None:
                    current_source_y = source_y
                elif source_y != current_source_y:
                    flush_row()
                    current_source_y = source_y
                current_row_widgets.append(widget)
            flush_row()

        # Set screen height to the actual widget extent so collision-resolved
        # widgets remain visible instead of being clipped below the viewport.
        screen_width = self.DEFAULT_SCREEN_WIDTH
        screen_height = self.DEFAULT_SCREEN_HEIGHT
        for w in widgets:
            wx = int(w["nxcoord"]) + int(w["nwidth"])
            screen_width = max(screen_width, wx)
            wy = int(w["nycoord"]) + int(w["nheight"])
            screen_height = max(screen_height, wy)
        screen_height = min(screen_height, 60)

        palette_final = str(self.palette_id) if self._palette_colors else "4"
        for widget in widgets:
            xp = widget.get("xparams", "")
            if "__PALETTE__" in xp:
                widget["xparams"] = xp.replace("__PALETTE__", palette_final)
            widget.pop("_layout_x", None)
            widget.pop("_layout_y", None)

        self._build_screen_elements(data, widgets, screen_width, screen_height, palette_final, palette_name)

        # --- User sources (t11, t12, t13, t121, setusersource) ---
        # Raw widget datasets remain available for widgets/reports.
        raw_dm_source_registry: List[Dict[str, Any]] = []
        for ds in widget_datasets:
            ds_name = ds["name"]
            source_name = self._with_suffix(ds_name)
            ds_columns = ds["columns"]
            ds_rows = ds["rows"]
            stable = dataset_stable_map.get(ds_name) or self._dataset_stable(
                self._with_suffix(ds_name)
            )
            source_id = self._emit_user_source(
                data=data,
                t11=t11,
                t12=t12,
                dv=dv,
                sources_info=sources_info,
                source_name=source_name,
                stable=stable,
                columns=ds_columns,
                rows=ds_rows,
                dt_last_load=dt_last_load,
                view_query=ds.get("_view_query") if isinstance(ds.get("_view_query"), str) else None,
                view_level=int(ds.get("_view_level") or 0),
            )
            if not ds.get("_exclude_from_datamodel"):
                raw_dm_source_registry.append({
                    "source_id": source_id,
                    "name": source_name,
                    "columns": ds_columns,
                    "rows": ds_rows,
                })

        # Semantic sources drive the exported Navigator data model.
        dm_source_registry: List[Dict[str, Any]] = []
        for semantic in self.semantic_sources:
            logical_name = str(semantic.get("logical_name") or "").strip()
            columns = semantic.get("columns") if isinstance(semantic.get("columns"), list) else []
            rows = semantic.get("rows") if isinstance(semantic.get("rows"), list) else []
            if not logical_name or not columns:
                continue
            source_name = self._with_suffix(logical_name)
            stable = self._dataset_stable(source_name)
            source_id = self._emit_user_source(
                data=data,
                t11=t11,
                t12=t12,
                dv=dv,
                sources_info=sources_info,
                source_name=source_name,
                stable=stable,
                columns=columns,
                rows=rows,
                dt_last_load=dt_last_load,
            )
            dm_source_registry.append({
                "source_id": source_id,
                "name": source_name,
                "columns": columns,
                "rows": rows,
                "_logical_name": logical_name,
                "_semantic_role": semantic.get("_semantic_role"),
                "_join_to": semantic.get("_join_to"),
                "_is_consolidated_kpi": logical_name == "FactObservation",
            })

        if not dm_source_registry:
            dm_source_registry = raw_dm_source_registry

        # t13 - data.tusersourcefileuploadtemplate (empty)
        ET.SubElement(data, "t13", attrib={"sCheck": "0"})

        # t121 - data.tusersourcetransformation (empty)
        ET.SubElement(data, "t121", attrib={"sCheck": "0"})

        # --- Data model (t70..t75, t100) ---
        self._build_data_model(
            data, datamodel_info, dm_source_registry,
        )

        # --- Queue jobs stubs (t80..t85) ---
        ET.SubElement(data, "t80", attrib={"sCheck": "0"})   # queue.tjobs
        ET.SubElement(data, "t81", attrib={"sCheck": "0"})   # queue.tjobsteps
        ET.SubElement(data, "t82", attrib={"sCheck": "0"})   # queue.tjobconditions
        ET.SubElement(data, "t83", attrib={"sCheck": "0"})   # queue.tjobconditionresults
        ET.SubElement(data, "t84", attrib={"sCheck": "0"})   # queue.tscheduler
        ET.SubElement(data, "t85", attrib={"sCheck": "0"})   # rme.tsubjectareajobs

        # --- <d> section with table definitions ---
        self._build_d_section(root)

        # Safety net: if model blocks were accidentally duplicated,
        # keep one coherent data model with matching dependencies.
        self._normalize_datamodel_sections(root)

        return ET.tostring(root, encoding="utf-8", xml_declaration=True)
